### ISSUE TITLE
New Translation Progress Checklist

### ISSUE THREAD

**Issue by no-yan** [reactjs/ja.react.dev#452]
# ページを翻訳したい方へ：
重複作業を防ぐため、まずはここでどのページを翻訳するか宣言してください。宣言なしで翻訳が行われて他の人の作業と被ってしまった場合、**原則として（PRを先に作った人ではなく）ここで最初に宣言があった人を優先します**。ただし宣言が行われて 1 週間以上 PR が作成されないなどの場合は適宜対応します。

[スタイルガイド](https://github.com/reactjs/ja.react.dev/wiki/%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)および[単語リスト](https://github.com/reactjs/ja.reactjs.org/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80)をチェックして、翻訳が一貫した方法で書かれていることを確認してください。

# New Articles

Progress : (🏃 進行中の作業; 👀 レビュー中）

## Main Content 

To do before releasing as an "official" translation. **Please translate these pages first.**

Note that each section has an index page, which needs to be translated too.

### Learn React

- [x] Quick Start (@smikitky #559)
  - [x] Tutorial: Tic Tac Toe (@smikitky #562)
  - [x] Thinking in React (@smikitky #560)
  
- [x] Installation (@smikitky, #555)
  - [x] Start a New React Project (@smikitky, #555)
  - [x] Add React to an Existing Project (@smikitky, #555)
  - [x] Editor Setup (@smikitky, #555)
  - [x] Using TypeScript (@smikitky, #659)
  - [x] React Developer Tools (@smikitky, #555)
  
- [x] Describing the UI (@smikitky #556)
  - [x] Your First Component (@smikitky, #451)
  - [x] Importing and Exporting Components (@smikitky, #451)
  - [x] Writing Markup with JSX (@smikitky #459)
  - [x] JavaScript in JSX with Curly Braces (@smikitky #459)
  - [x] Passing Props to a Component (@smikitky #461)
  - [x] Conditional Rendering (@smikitky #556)
  - [x] Rendering Lists (@smikitky #556)
  - [x] Keeping Components Pure (@smikitky #556)
  
- [x] Adding Interactivity (@pasteisdenata, #491)
  - [x] Responding to Events (@smikitky, #567)
  - [x] State: A Component's Memory (@smikitky, #567)
  - [x] Render and Commit (@smikitky, #567)
  - [x] State as a Snapshot (@smikitky, #569)
  - [x] Queueing a Series of State Updates (@smikitky, #569)
  - [x] Updating Objects in State (@smikitky, #574)
  - [x] Updating Arrays in State (@smikitky, #574)
  
- [x] Managing State (@smikitky, #610)
  - [x] Reacting to Input with State (@youliangdao, #571)
  - [x] Choosing the State Structure (@smikitky, #588)
  - [x] Sharing State Between Components (@smikitky, #582)
  - [x] Preserving and Resetting State (@smikitky, #583)
  - [x] Extracting State Logic into a Reducer (@smikitky, #584)
  - [x] Passing Data Deeply with Context (@smikitky, #586)
  - [x] Scaling Up with Reducer and Context (@smikitky, #587)
  
- [x] Escape Hatches (@smikitky, #620)
  - [x] Referencing Values with Refs (@smikitky, #590)
  - [x] Manipulating the DOM with Refs (@smikitky, #589)
  - [x] Synchronizing with Effects (@smikitky, #594)
  - [x] You Might Not Need an Effect (@smikitky, #604)
  - [x] Lifecycle of Reactive Effects (@yuta-ike, #601)
  - [x] Separating Events from Effects (@kotaesaki, #609)
  - [x] Removing Effect Dependencies (@smikitky, #611)
  - [x] Reusing Logic with Custom Hooks (@smikitky, #605)

### API Reference

- [x] `react`: Hooks (@Hayao0819, #618)
  - [x] `use` (@smikitky, #687)
  - [x] `useCallback` (@seckie, #591)
  - [x] `useContext` (@jp-knj, #621)
  - [x] `useDebugValue` (@seckie, #573)
  - [x] `useDeferredValue` (@smikitky, #622)
  - [x] `useEffect` (@smikitky, #568)
  - [x] `useId` (@sbasken, #608)
  - [x] `useImperativeHandle` (@sbasken, #614)
  - [x] `useInsertionEffect` (@smikitky, #625)
  - [x] `useLayoutEffect` (@smikitky, #624)
  - [x] `useMemo` (@yuta-ike, #643)
  - [x] `useReducer` (@locol23, #641)
  - [x] `useRef` (@yuta-ike, #613)
  - [x] `useState` (@yuta-ike, #595)
  - [x] `useSyncExternalStore` (@jp-knj, #619)
  - [x] `useTransition` (@smikitky, #623)

- [x] `react`: Components (@smikitky, #686)
  - [x] `<Fragment> (<>)` (@jp-knj, #626)
  - [x] `<Profiler>` (@smikitky, #629)
  - [x] `<StrictMode>` (@smikitky, #630)
  - [x] `<Suspense>` (@smikitky, #628)

- [x] `react`: APIs (@natsuokawai, #636)
  - [x] `cache` (@locol23, #696)
  - [x] `createContext` (@natsuokawai, #638)
  - [x] `forwardRef` (@smikitky, #631)
  - [x] `lazy` (@smikitky, #633)
  - [x] `memo` (@smikitky, #702)
  - [x] `startTransition` (@smikitky, #623)

- [x] `react`: Directives (@smikitky, #635)
  - [x] `'use client'` (@smikitky, #635)
  - [x] `'use server'` (@smikitky, #635)

- [x] `react-dom`: Components (@smikitky, #682)
  - [x] Common (e.g. `<div>`) (@smikitky, #637)
  - [x] `<input>` (@sbasken, #646)
  - [x] `<option>` (@smikitky, #678)
  - [x] `<progress>` (@natsuokawai, #640)
  - [x] `<select>` (@ainoshment, #644)
  - [x] `<textarea>` (@smikitky, #649)

- [x] `react-dom`: APIs (@smikitky, #681)
  - [x] `createPortal` (@smikitky, #647)
  - [x] `flushSync` (@smikitky, #650)
  - [x]  `findDOMNode` (@jp-knj, #670)
  - [x] `hydrate` (@riku929hr, #653)
  - [x] `render` (@smikitky, #663)
  - [x] `unmountComponentAtNode` (@smikitky, #660)

- [x] `react-dom/client`: Client APIs (@smikitky, #662)
  - [x] `createRoot` (@smikitky, #661)
  - [x] `hydrateRoot` (@smikitky, #669)

- [x] `react-dom/server`: Server APIs (@smikitky, #656)
  - [x] `renderToNodeStream` (@smikitky, #655)
  - [x] `renderToPipeableStream` (@smikitky, #654)
  - [x] `renderToReadableStream` (@smikitky, #654)
  - [x] `renderToStaticMarkup` (@smikitky, #655)
  - [x] `renderToStaticNodeStream` (@smikitky, #655)
  - [x] `renderToString` (@smikitky, #655)

### Navigation and UI

We suggest to leave *most* of the UI translation until the end. We plan to do some invasive changes to the website folder layout and components, so postponing this until your translation is almost complete would make it easier to merge the changes from our side later. It might make sense to translate the homepage above the fold early, but leave the rest for later. As individual pages get translated, you can change the page titles in the corresponding sidebar files. Finally, when you're translating the navigation, make sure to test both desktop and mobile layouts.

- [x] Homepage (currently in `HomeContent.js`) (@smikitky, #570)
- [x] Sidebars (currently in `src/sidebar*.json`) (@smikitky, #658)
- [x] Top-level navigation (currently in `TopNav.tsx`) (やらない)

### When You're Ready...

After everything above is translated, add your language to `deployedLanguages` in `Seo.tsx` of the original [reactjs/react.dev](https://github.com/reactjs/react.dev) repository.

## Secondary Content 

These API pages should ideally be translated too, but they're less urgent and can be done after the others:

- [x] Legacy React APIs (@smikitky, #693)
  - [x] `Children` (@smikitky, #684)
  - [x] `cloneElement` (@smikitky, #685)
  - [x] `Component` (@smikitky, #677)
  - [x] `createElement` (@smikitky, #688)
  - [x] `createFactory` (@smikitky, #690)
  - [x] `createRef` (@smikitky, #689)
  - [x] `isValidElement` (@smikitky, #691)
  - [x] `PureComponent` (@smikitky, #692)

## Optional Content 

These aren't the main translation targets, but if you'd like to do them, feel free to expand the list to include their subpages:

- [x] Community (@smikitky, #668)
- [x] Blog
- [ ] Warnings

**Comment by noyanyan** [comment]
進捗管理用のissueが閉じられていたので、新規issueを開きました。気軽に閉じてください。

この形式でやる場合の懸念点として、Statusの更新が面倒になる可能性があります。どれが更新かわかるようにupstream側で配慮があればよいですが、そうでない場合は頑張って40近いリストから差分を見つける必要がありそうです。

**Comment by smikitky** [comment]
既に[ちょっと手を付けてはいる](https://github.com/reactjs/ja.reactjs.org/pull/451)のですが、まだブランチプレビューがセットアップされておらず、textlint も動いておらず、本家の方でも認識していなかった[細々とした問題が見つかったり](https://github.com/reactjs/reactjs.org/issues/4135#issuecomment-983299336)…という状況ですので、ひとまずワークフローを確立するのが先決という状況です。

これで大丈夫そうというところで以前のように翻訳者を募集することになると思いますので、しばらくお待ちください。

**Comment by pasteisdenata** [comment]
こんにちは。技術翻訳をしている者です。オープンソースのプロジェクトに関わった経験はないのですが、是非お手伝いしたく、よろしくお願いします。既にフォークは作成済みです。どのセクションの翻訳から開始すればよいですか。

**Comment by no-yan** [comment]
（メンテナの方々からお返事がないようなので）
ありがとうございます！技術翻訳をされている方ということで心強いです。
"Escape Hatches" 以外のまだ訳されていないセクションを自由に訳していただければと思います。

用語が合っているか既存の訳と照らし合わせたいようなら "Installation" から、そうでなければ "Adding Interactivity", "Managing State", "Quick Start" のいずれかを選んで頂くと良いと思います！

上のチェックリストも更新しておきます。

**Comment by no-yan** [comment]
場合によっては、React 18用の大規模なドキュメント更新がこちらより優先されるかもしれません。
以下のドラフトがマージされて以降になりますが、そちらもご助力いただければ！
https://github.com/reactjs/reactjs.org/pull/4499

**Comment by smikitky** [comment]
@pasteisdenata @no-yan すみません気付いていませんでした…。

React 18 用の大規模マージについては認識はしています。これはむしろ私（メンテナ）の方でやります（影響範囲大きそうすぎるので逆に自分で確認しながら進めたい）。

ベータドキュメントについても、現時点ではワークフローの準備が整っていないため大々的に進めていない状態です。ただ上記に書いてある技術的問題は概ね解決しそうですので、これから改めて進めていきたいと思っています。ひとまず上記でチェックのついていないものならどれからやっていただいても大丈夫ですが、重複作業を防ぐため、このページで着手するという宣言だけしてください。

なお、本家の方でも新ドキュメントの作業が結構遅れており[こんなこと](https://github.com/reactjs/reactjs.org/issues/3308#issuecomment-1051055907)を言われている状況です。恐らく React 18 のリリースも終わったので進み始めるだろうとは思っているのですが、いろいろ流動的なところがある点についてはご了承ください。

**Comment by pasteisdenata** [comment]
@smikitky @no-yan  レスポンスが遅れてしまい申し訳ありません。では、Adding Interactivity から開始しますね。取り急ぎ。

**Comment by pasteisdenata** [comment]
@smikitky Responding to Events の翻訳を始めます。

**Comment by k98a73** [comment]
@potato4d @koba04 @smikitky @no-yan @pasteisdenata
初めまして。こちらの翻訳活動プロジェクトに参加させていただきます。
よろしくお願いします。
Start a New React Project の翻訳を進めていきます。

**Comment by gaearon** [comment]
Hi folks,

Just a heads-up that we've done our best to bring `main` and `legacy` branches up-to-date with upstream. This brings you to the latest visual design and sets up all the redirects. We don't anticipate more changes necessary on `legacy`. For `main`, there's a few things you need to be aware of:

- Keep in mind translating UI is best done closer to the end. We plan to make non-trivial code changes to the repo over the next few months. So it's best to focus on the content rather than on UI components.
- The homepage is untranslated so ideally it would be good if you could do a pass at that. For now, unfortunately it requires messing with the code file.
- A few rewritten pages (from Installation) are currently untranslated.
- This was a massive PR to merge, so we might have regressed somewhere or missed some changes that needed to be translated. Ideally, it would be great if you could go over the already-translated pages at your own pace and verify nothing important got lost.

Thank you so much for your cooperation!

**Comment by gaearon** [comment]
With `legacy`, there's some inconsistencies with how the red banners are displayed/translated. Sorry about that. We've added them manually where they were missing, but they might need a manual pass to make it nicer.

**Comment by gaearon** [comment]
I've updated the task list to match our main template.

**Comment by gaearon** [comment]
@smikitky Is the maintainer list in https://github.com/reactjs/translations.react.dev still accurate? If not, would you mind sending a PR that brings it up to date? Thanks!

**Comment by smikitky** [comment]
@gaearon Yes it's accurate, thanks!

**Comment by smikitky** [comment]
@yuta-ike ありがとうございます。

- 詳しく読んでいないのですが[こちらの state 紹介記事](https://ja.react.dev/learn/state-a-components-memory)やその後の数記事と同じコラムや文章がまるごと文章がコピーされていたりすることがあるので、その場合はそちらから訳文をコピーしていただけると助かります。
- PR を作る前に main をマージするか main にリベースしてください。[こちらの Wiki](https://github.com/reactjs/ja.react.dev/wiki) で説明している textlint 関係の更新が含まれています。

**Comment by yuta-ike** [comment]
`Lifecycle of Reactive Effects` のページの翻訳を行います。

**Comment by sbasken** [comment]
初めまして😄　ソフトウェアエンジニア＆翻訳をしているものです。freeCodeCamp.org で Trello を使った翻訳作業は今年３月からしています。 github では初めてですが、貢献できたらと思います。すでに fork はしました。優先的に翻訳した方が良いページはありますか？

**Comment by smikitky** [comment]
@sbasken ありがとうございます。どこからでも構わないのですが、需要が高いのはフックリファレンスかなと思います。短いのから始めたい場合は useId などの learn セクションでカバーされていないもの、がっつりやる場合は useContext などは如何でしょう。

**Comment by sbasken** [comment]
@smikitky フックリファレンスから取り掛かってみます！ありがとうございます😊

**Comment by yuta-ike** [comment]
@smikitky  `useRef` の翻訳を行います。

**Comment by sbasken** [comment]
@smikitky `useImperativeHandle` のページの翻訳に取り組んでもいいでしょうか？

**Comment by Hayao0819** [comment]
@smikitky こんにちは。初めての翻訳なのですが、`react: Hooks`(`src/content/reference/react/index.md`)の翻訳に取り組んでもよろしいでしょうか？

**Comment by smikitky** [comment]
@Hayao0819 ありがとうございます。目次系の記事は他の記事の翻訳が終わった後に整合性のための調整がちょっと入るかもしれませんので、そのときはご了承ください。

(あと英文と日本語の間にはスペースをお願いします)

**Comment by Hayao0819** [comment]
@smikitky 整合性のための調整の件、了解しました。

>(あと翻訳記事の英語と日本語の間にはスペースをお願いします)

の部分がよくわかってないのですが、どういうことでしょうか？

**Comment by smikitky** [comment]
@Hayao0819 [これ](https://twitter.com/Hayao0819/status/1674662814164848640)が見えちゃったので、[英数字と和文との間には半角スペースを入れる](https://github.com/reactjs/ja.react.dev/wiki/%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)というルールの遵守をお願いしますということでした…分かりづらくてすみません

**Comment by Hayao0819** [comment]
@smikitky  そういうことだったんですね。後から気付いて修正済みです。

**Comment by jp-knj** [comment]
@smikitky はじめまして！Hooks の [useSyncExternalStore](https://github.com/reactjs/ja.react.dev/blob/main/src/content/reference/react/useSyncExternalStore.md) の翻訳に取り組んでもよろしいでしょうか？

作業を始める前に一点ほど、確認したいことがあります。
Issue にある表記ルールのリンクが切れており、確認できませんでした。
> [表記ルール](https://github.com/reactjs/ja.reactjs.org/blob/main/TRANSLATION.md)をチェックして、翻訳が一貫した方法で書かれていることを確認してください。


wiki にある [翻訳スタイルガイド](https://github.com/reactjs/ja.react.dev/wiki/%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)を確認しながらの翻訳作業でも問題ないでしょうか？

**Comment by jp-knj** [comment]
`useContext` の翻訳を行います。

**Comment by smikitky** [comment]
@jp-knj よろしくお願いします！ リンク切れについても修正しました。Wiki が最新版です。

**Comment by yuta-ike** [comment]
@smikitky `useMemo` の翻訳を行います

**Comment by locol23** [comment]
@smikitky こんにちは！古い方のドキュメントで [Context](https://github.com/reactjs/ja.react.dev/pull/59) を翻訳したものです。新しい方のドキュメントの翻訳が始まっていそうだったので、検索してこの Issue に辿り着きました！今からですと、Hooks の `useReducer` を翻訳する感じが良いでしょうか？それとも、他に優先して翻訳した方が良い部分などあるでしょうか 🙇

**Comment by jp-knj** [comment]
`<Fragment> (<>)` を翻訳を行います。

**Comment by smikitky** [comment]
@locol23 ありがとうございます。useReducer でよろしくお願いします。

**Comment by natsuokawai** [comment]
React APIのインデックスページとcreateContextの翻訳を行います

**Comment by natsuokawai** [comment]
React API の memo の翻訳を行います

**Comment by smikitky** [comment]
@natsuokawai もう作業をされていますか？　実は `memo` は `useMemo` と記載が被っている部分が結構あり（特に "Should you add memo everywhere?" の部分）、できれば同じ方に翻訳してもらうのがいいかなと思って少し後回しにしていました。

**Comment by natsuokawai** [comment]
@smikitky 
いえ、まだです。そういった背景があって残っていたのですね。
そうしましたら上記のコメントは取り消しておきます。

**Comment by smikitky** [comment]
@yuta-ike 上記の通りなのですが、useMemo が終わったあとに memo をお願いしても大丈夫でしょうか。特に急ぎません。

**Comment by yuta-ike** [comment]
@smikitky 承知しました👍

**Comment by Hayao0819** [comment]
@smikitky  react-dom Componentsの`option`の翻訳を行っても良いでしょうか？

**Comment by sbasken** [comment]
@smikitky `react-dom: Components` の　`<input>`　の翻訳を行います。

**Comment by natsuokawai** [comment]
`react-dom: Components` の `<progress>` の翻訳を行います。

**Comment by jp-knj** [comment]
`react-dom: APIs` の `createPortal` の翻訳を行います。

**Comment by ainoshment** [comment]
@smikitky こんにちは。 `react-dom: Components` の `<select>` の翻訳に取り組んでみてもよろしいでしょうか？

**Comment by smikitky** [comment]
renderToX 系はコピペがすごそうなので1名でやります

**Comment by jp-knj** [comment]
`react-dom: APIs` の `findDOMNode` の翻訳を行ってよろしいでしょうか？
他に推奨があれば、そちらを着手します！

**Comment by riku929hr** [comment]
@smikitky 
はじめまして。`react-dom: APIs` の hydrate の翻訳を行ってもよろしいでしょうか？

**Comment by smikitky** [comment]
@Hayao0819 `<option>` の翻訳はどんな感じでしょうか。もう残り記事も少ないですし、こちらで引き取ることも可能です。

**Comment by Hayao0819** [comment]
@smikitky すみませんすっかり忘れていました。本当に申し訳ないです。そちらでお願いしてもよろしいでしょうか？

**Comment by locol23** [comment]
@smikitky `react: APIs` の `cache` の翻訳を行っても良いでしょうか？

**Comment by smikitky** [comment]
現状の全記事の翻訳 (experimental なのを除く) が終了したので close します！ ありがとうございました！

**Comment by smikitky** [comment]
これを close すると https://translations.react.dev/ がうまく動いていないっぽいのでとりあえず reopen します…なぜ…

**Comment by smikitky** [comment]
新しい翻訳が追加されるたびに reopen するのもアレなのでこちらは当面 open にしておきます。

ちなみに translations.react.dev はブラウザから GitHub に以下のような GraphQL クエリを発行してその結果を解析することで動作していました。なのでこれを close してしまうと進行状況が不明になってしまうということのようです。なんという力業…。

<details>
<summary>GraphQL クエリ</summary>

```graphql
query($limit: Int!) {
  search(
    type: ISSUE
    query: "org:reactjs Translation Progress in:title is:open"
    first: $limit
  ) {
    nodes {
      ... on Issue {
        title
        body
        createdAt
        lastEditedAt
        number
        repository {
          name
        }
      }
    }
  }
}
```

</details>

**Comment by islaree** [comment]
@smikitky 
ロゴ横のv19を押下して遷移することができるページ (https://ja.react.dev/versions) の翻訳がされていないようです。
対応漏れでしたら、翻訳をしていただけますと幸いです。
![Image](https://github.com/user-attachments/assets/70d37321-42ab-461d-8a05-d1bf941ddd6f)

**Comment by smikitky** [comment]
@islaree 確かに漏れていましたので #834 で対応します。ありがとうございました。

**Comment by r-kojima** [comment]
@smikitky 
初めまして。ドキュメントを読んでいたところ、[`flushSync`のドキュメント](https://ja.react.dev/reference/react-dom/flushSync#caveats) に一部翻訳もれを見つけました。こちらの翻訳を対応してもよろしいでしょうか？
細かくて申し訳ありませんが、よろしくお願いします。

**Comment by smikitky** [comment]
@r-kojima 気付いていませんでした、ありがとうございます！

#873 で対応します。
次回からは普通に新しく Issue を立てていただいて OK です。

**Comment by kenji-arata** [comment]
react-compilerのreference記事のconfigrationページの翻訳作業を行います。
具体的なpathで言うと、以下になります。
* `/reference/react-compiler/configuration`
* `/reference/react-compiler/compilationMode`
* `/reference/react-compiler/gating`
* `/reference/react-compiler/logger`
* `/reference/react-compiler/panicThreshold`
* `/reference/react-compiler/target`
