### ISSUE TITLE
Establish beta translation workflow

### ISSUE THREAD

**Issue by smikitky** [reactjs/ja.react.dev#453]
Now that the main contents of [New React Docs](https://beta.reactjs.org/) are mostly stable, translators can start translating many articles. There are a few tasks to complete before we can start a full-scale translation work.

- [x] #580
- [x] #581 
- [x] Recheck glossary
- [x] Make translation progress list: #452
- [x] Merge reactjs/reactjs.org#4139 (this affects translation workflow)

Not urgent:

- [ ] Fix italic issues (#94)
- [ ] Switch to a better-looking Japanese font

**Comment by smikitky** [comment]
12/22現在、以下の2点が未解決です

- **PRを作成するとあらゆるCIこける**: 原因をつきとめたので upstream で修正済み、こちらへの取り込み待ち (reactjs/reactjs.org#4192)
- **textlint のセットアップ**: サブディレクトリに husky で pre-commit フックをセットアップした時に何らかの環境依存でエラーが起こっており、それの修正が必要

これらが解決したら本格的に全記事の翻訳にとりかかっていいかなと思います

**Comment by AsazuTaiga** [comment]
@smikitky こんにちは！react.devも正式ローンチされたので、翻訳のお手伝いしたいなと思ったのですが、何かアップデート／お手伝いできることはありますか？

**Comment by smikitky** [comment]
@AsazuTaiga すみません、実は試しに ChatGPT に Markdown を翻訳させてそれを少々手直しして使うということをやってみたら、自分の想像以上に快適かつ正確な感じになり、「こりゃ先にこれをリリースしてみんなに使ってもらう方がいいんじゃないか」と思っているところです。もちろん所詮機械翻訳なのでそこそこに手直しは要るのですが、それでも人間がゼロから翻訳するのが馬鹿らしくなる程度の性能は出ています。

そろそろ公開できそうなところまでその翻訳ソフトの準備の方はできているので、それが出来てから手直しの部分だけやってもらうか、もういっそ自分で全部やっちゃうか…という感じになっています。もうちょっとお待ちください。

**Comment by smikitky** [comment]
メインの Learn セクションの翻訳は半分以上終わっているところではありますが、#580 と #581 が終わったら以前のようにもう少し大々的に翻訳者を募集していいかなと思っています。

それはそうと、ここを見ていただいているような方は #452 や Wiki を見て作業をしていただいても大丈夫です。

**Comment by smikitky** [comment]
とりあえず以前と同様以上の環境には戻ったと思われますので close したいと思います。

残りのフォント問題は別 issue にしました。

- #599
